import {
  ArrowDown,
  Flame,
  Eye,
  RotateCcw,
  DollarSign,
  Zap,
  Wind,
  Lock,
  AlertTriangle,
  Users,
  ClipboardCheck,
  Shield,
  Plus,
} from 'lucide-react';

export const operations = [
  { id: 'mint', label: 'Mint', icon: Plus, href: 'mint', color: 'bg-green-100' },
  { id: 'burn', label: 'Burn', icon: Flame, href: 'burn', color: 'bg-red-100' },
  {
    id: 'transfer',
    label: 'Transfer',
    icon: ArrowDown,
    href: 'transfer',
    color: 'bg-blue-100',
  },
  { id: 'getbalance', label: 'Get Balance', icon: Eye, href: '#', color: 'bg-purple-100' },
  { id: 'cashin', label: 'Cash in', icon: ArrowDown, href: '#', color: 'bg-slate-100' },
  { id: 'rescue', label: 'Rescue', icon: RotateCcw, href: '#', color: 'bg-slate-100' },
  { id: 'rescuehbars', label: 'Rescue HBARs', icon: DollarSign, href: '#', color: 'bg-slate-100' },
  { id: 'wipe', label: 'Wipe', icon: Zap, href: '#', color: 'bg-slate-100' },
  { id: 'freezeaccount', label: 'Freeze account', icon: Lock, href: '#', color: 'bg-slate-100' },
  { id: 'unfreeze', label: 'Unfreeze', icon: Wind, href: '#', color: 'bg-slate-100' },
  { id: 'checkfrozen', label: 'Check account frozen status', icon: Lock, href: '#', color: 'bg-slate-100' },
  { id: 'kyc', label: 'Grant KYC', icon: Users, href: '#', color: 'bg-slate-100' },
  { id: 'revokekyc', label: 'Revoke KYC', icon: ClipboardCheck, href: '#', color: 'bg-slate-100' },
  { id: 'checkkyc', label: 'Check KYC', icon: Shield, href: '#', color: 'bg-slate-100' },
  { id: 'danger', label: 'Danger Zone', icon: AlertTriangle, href: '#', color: 'bg-slate-100' },
];
